---
driver:
  name: vagrant

provisioner:
  name: ansible

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      hosts: localhost
      playbook: tests/test.yml
      additional_copy_path:
        - "."
